### ISSUE TITLE
Não funciona com o sigaa da UFRB

### ISSUE THREAD

**Issue by vxfontes** [GeovaneSchmitz/SIGAA-node-interface#31]
O sigaa da ufrb tem url: https://sistemas.ufrb.edu.br.
Ao tentar apenas efetuar o login, aparece o seguinte erro: 

`C:\Users\nessa\Desktop\coding\reactjs\sigaa\ok\node_modules\sigaa-api\src\session\login\sigaa-login-ifsc.ts:93
        throw new Error(this.errorInvalidCredentials);
              ^
Error: SIGAA: Invalid credentials.
    at SigaaLoginIFSC.parseDesktopLoginResult (C:\Users\nessa\Desktop\coding\reactjs\sigaa\ok\node_modules\sigaa-api\src\session\login\sigaa-login-ifsc.ts:93:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at SigaaLoginIFSC.desktopLogin (C:\Users\nessa\Desktop\coding\reactjs\sigaa\ok\node_modules\sigaa-api\src\session\login\sigaa-login-ifsc.ts:65:12)
    at SigaaLoginIFSC.login (C:\Users\nessa\Desktop\coding\reactjs\sigaa\ok\node_modules\sigaa-api\src\session\login\sigaa-login-ifsc.ts:77:20)
    at Sigaa.login (C:\Users\nessa\Desktop\coding\reactjs\sigaa\ok\node_modules\sigaa-api\src\sigaa-main.ts:309:18)
    at main (C:\Users\nessa\Desktop\coding\reactjs\sigaa\ok\node_modules\sigaa-api\src\sigaa-main.ts:353:19)
[nodemon] app crashed - waiting for file changes before starting...`

**Comment by dduartee** [comment]
hum, estranho
Não deveria dar erro, caso o login esteja realmente correto.
Ambos parametros dos formulários são identicos...

UFRB
![image](https://user-images.githubusercontent.com/45330928/205194795-bd820eff-7265-4e88-a31d-034710aa4f5c.png)

IFSC
![image](https://user-images.githubusercontent.com/45330928/205194937-399f51e4-66b0-48cc-aa90-bcf77b660fe9.png)

pode conferir se realmente o usuário e senha estão certos?

**Comment by vxfontes** [comment]
estão sim, inclusive testei com o usuário e senha de outra pessoa para ver se realmente era problema meu

**Comment by dduartee** [comment]
Criei uma branch #32 para modificar e testar o seu acesso.
Para instalar caso use yarn: 
`yarn add "GeovaneSchmitz/sigaa-api#pull/32/head"`
caso use npm: 
`npm install "GeovaneSchmitz/sigaa-api#pull/32/head"`

e lembre-se de colocar o parâmetro institution
![image](https://user-images.githubusercontent.com/45330928/205444249-83132358-d496-4e04-9680-897886f2ef7e.png)

Eu investiguei as requisições até onde consigo ir, não tem nenhuma diferença.
O que eu sugiro é tentar debugar o código direto do node_modules/ e comparar com as requisições do navegador normal.
O metódo que está retornando erro é este: `linha 106 de /session/login/sigaa-login-ufrb.js`
![image](https://user-images.githubusercontent.com/45330928/205444399-9bc75b71-b509-4d04-88e0-711227443227.png)
ou seja, a página pós login contém o "Entrar no Sistema" e "Usuário e/ou senha inválidos", o que é estranho.

antes do `const accountPage = ....` coloque o `console.log(page.requestBody)`, ele retornará no console os parâmetros enviados no post da requisição, sairá algo como isto
```url
width=0&height=0&urlRedirect=&subsistemaRedirect=&acao=&acessibilidade=&user.login=SEU_USUARIO&user.senha=SUA_SENHA
```
Obviamente, **não** coloque ele aqui pois contém o seu login, apenas veja se está correto.

Caso esteja correto, vamos precisar comparar com as requisições do navegador pelo inspecionar elemento (F12), na aba network, clique na engrenagem na direita
![image](https://user-images.githubusercontent.com/45330928/205445410-7bbe43eb-6078-4ad2-b9de-7b675bee72c2.png)
e habilite a primeira opção (Persist Logs)
Volte para a página e coloque seu login e faça o login.

Selecione o primeiro da lista (POST)
![image](https://user-images.githubusercontent.com/45330928/205445498-0d10ba6a-372d-480b-8574-5891993ee279.png)

Detalhe, o meu statusCode foi 200, por causa que me retornou direto a página de erro, mas se o login tiver sucesso ele geralmente será 302.

Ao lado entre na aba Request e ali estará os dados enviados da requisição
![image](https://user-images.githubusercontent.com/45330928/205445741-40f0df59-e61e-4dc4-a02d-e8d0da131979.png)

Verifique se eles são iguais aos retornados pelo console.

**Comment by dduartee** [comment]
Olá, conforme a issue #36, acredito que estejam tratando do mesmo problema.

Se possível, peço que ao invés de instalar a biblioteca da forma normal, instale da seguinte forma:

**Com as aspas!**
```console
yarn add "https://github.com/GeovaneSchmitz/sigaa-api/"
```
ou com o npm
```console
npm install "https://github.com/GeovaneSchmitz/sigaa-api/"
```

Possivelmente o código no npm está com desatualizado em relação ao repositório do GitHub, visto que na issue #36 há um bug que exibe a mesma mensagem de erro, inclusive nos meus testes com o SIGAA do IFSC.

Caso seja esse o problema, terá que usar temporariamente a biblioteca direto pelo github até que seja resolvido.
Não custa tentar :)
